# Generated by Django 4.0.10 on 2023-03-12 20:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to=mainapp.models.get_author_photo_path)),
                ('brief', models.TextField(max_length=200, null=True)),
                ('about', models.TextField(max_length=500)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=700)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=mainapp.models.get_book_cover_path)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Novel', 'Novel'), ('History', 'History'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Self-help', 'Self-help'), ('Poetry', 'Poetry'), ('Romance', 'Romance'), ('Religious', 'Religious')], max_length=20, null=True)),
                ('year', models.IntegerField()),
                ('nbr_pages', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=70)),
                ('img_cap', models.ImageField(blank=True, null=True, upload_to='cover')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.publisher'),
        ),
    ]
