# Generated by Django 4.0.10 on 2023-03-02 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pfp', models.ImageField(null=True, upload_to='pfp')),
                ('brief', models.TextField(max_length=200, null=True)),
                ('about', models.TextField(max_length=500)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=70)),
                ('img_cap', models.ImageField(null=True, upload_to='cover')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=700)),
                ('cover', models.ImageField(null=True, upload_to='cover')),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Novel', 'Novel'), ('History', 'History'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Self-help', 'Self-help'), ('Poetry', 'Poetry'), ('Romance', 'Romance'), ('Religious', 'Religious')], max_length=20, null=True)),
                ('year', models.IntegerField()),
                ('nbr_pages', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.publisher'),
        ),
    ]
