# Generated by Django 4.0.10 on 2023-03-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='items',
            new_name='products',
        ),
    ]
