# Generated by Django 4.0.10 on 2023-03-06 20:57

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.get_author_photo_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.get_book_cover_path),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='img_cap',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
    ]
