# Generated by Django 4.0.10 on 2023-05-08 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Novel', 'Novel'), ('History', 'History'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Self-help', 'Self-help'), ('Poetry', 'Poetry'), ('Romance', 'Romance'), ('Religious', 'Religious'), ('Philosophy', 'Philosophy'), ('Science', 'Science')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.DeleteModel(
            name='BookRating',
        ),
    ]
