# Generated by Django 4.0.10 on 2023-04-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_comment_dislikes_comment_dislikes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
