# Generated by Django 4.0.10 on 2023-04-22 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_book_rating_bookrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'book')},
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
