# Generated by Django 4.0.10 on 2023-04-25 04:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_remove_book_rating_bookrating'),
        ('api', '0008_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'book')},
        ),
    ]
